# Generated by Django 4.0.4 on 2022-05-18 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_classify_delete_baby_delete_hero_delete_human'),
    ]

    operations = [
        migrations.CreateModel(
            name='responce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spam', models.IntegerField()),
            ],
        ),
    ]
